pool: Default

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: '.\WI.exe -s C:\ProgramData\HP\HP WebInspect\Settings\wiazure -r "Vulnerability" -y Standard -f C:\Users\Administrator\Desktop\test123456.pdf -gp'
      workingDirectory: 'C:\Program Files\Fortify\Fortify WebInspect'