pool: Default

steps:
  
- task: FortifyDynamicAssessment@7
  inputs:
    ScanSettings: 'wiazure'
    APIRoot: 'http://192.168.13.40:8083/'
    ScanResultsLocation: 'C:\Users\Administrator\Desktop\rapor'