pool: WIN-EL0NST4GT99

steps:
  
- task: FortifyDynamicAssessment@7
  inputs:
    ScanSettings: 'wiazure'
    APIRoot: 'http://192.168.13.142:8083'
    ScanResultsLocation: 'C:\Users\Administrator\Desktop\rapor'